title: Interaktiver Python Kurs
author: Dein Name
logo: ""

repository:
  url: https://github.com/<DEIN-GITHUB-NAME>/<DEIN-REPO-NAME>
  path_to_book: ""
  branch: main

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  thebe: true

execution:
  execute_notebooks: off # Schaltet die automatische Ausführung beim Bauen aus, spart Zeit

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js